services:
  dev-api:
    container_name: advlabs-api-dev
    restart: always
    ports:
      - '${API_PORT}:3000'
    build:
      context: .
      dockerfile: ./build/dev.dockerfile
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/src/app
    profiles: [dev]

  prod-api:
    container_name: advlabs-api-prod
    network_mode: host
    restart: always
    ports:
      - '${API_PORT}:3000'
    build:
      context: .
      dockerfile: ./build/prod.dockerfile
    depends_on:
      - db
      - redis
    profiles: [prod]

  db:
    container_name: advlabs-database
    image: postgres
    ports:
      - '${POSTGRES_PORT}:${DB_PORT}'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ${POSTGRES_PATH}/${PROJECT_NAME}/${POSTGRES_DATABASE}/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: advlabs-redis
    image: redis:6-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: always

volumes:
  data: {}
  redis_data: {}
